services:
  pizza-postgresql:
    image: postgres:17.2
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: userdb,paymentdb
      POSTGRES_USER: pizzauser
      POSTGRES_PASSWORD: pizzapwd

  pizza-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
